---
- name: Deploy K8s infrastructure and ArgoCD
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  roles:
    - helm-apps

- name: Deploy docker-compose apps
  hosts: microk8s
  become: true
  roles:
    - docker-apps
